Add default distribution in contracts
nortan-projetos/plataforma pull request #36
Opened 2021-08-31 20:35 UTC by leo-holanda

A distribuição dos contratos ocorre quando o mesmo é exibido. Se o contrato já possuir um time, a distribuição é feita levando em consideração esse time.

Mas, caso não tenha, a distruibição padrão será calculada de acordo com a quantidade de pessoas no time do orçamento. Anteriormente, a distribuição recebia "placeholders". 

Fiquei em dúvida se eu deveria ter incluído as funções de distribuição no service dos contratos ou deixar elas no contract-item mesmo.

2021-08-31 23:23 UTC, augustoicaro requested changes
Levantei alguns pontos sobre as alterações.

2021-08-31 23:23 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +  setDefaultDistribution(invoice: Invoice): void {
Essa função não deveria estar aqui, deveria estar no serviço do contrato e deveria ser chamada dentro da função de `saveContract` como haviamos conversado

2021-08-31 23:23 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +      2
A precisão precisa ser de 20 casas decimais como havíamos conversado

2021-08-31 23:23 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +      const invoiceFromService = this.getInvoiceFromService();
Esse não é um bom nome de variável. O que é um orçamento que veio do serviço? No fim o que você quer é converter um tipo que pode ser `Invoice | string | undefined` em `Invoice`.

2021-08-31 23:23 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +      return invoice ? invoice : undefined;
A função `idToInvoice` retorna sempre um Invoice. Essa linha sempre vai ser verdadeiro

2021-08-31 23:23 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +      if (invoiceFromService && invoiceFromService.team) {
Essa parte aqui só será necessária se não alterarmos o banco de dados para tratar os contratos que foram criados antes da implementação dos times. Hoje temos 154 contratos assim. Agora que fechamos a função de valor default, vamos considerar que todos contratos tem time e isso já vai vir tratado corretamente.

2021-09-02 16:56 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +  setDefaultDistribution(invoice: Invoice): void {
👍

2021-09-02 16:56 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +      2
👍

2021-09-02 16:56 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +      const invoiceFromService = this.getInvoiceFromService();
👍

2021-09-02 16:56 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +      return invoice ? invoice : undefined;
👍

2021-09-08 12:26 UTC, augustoicaro commented on src/app/shared/services/contract.service.ts
> +    const teamSize = invoice.team.length + 1;
Fazer cloneDeep do contrato para não alterar ele na função

2021-09-08 16:50 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +      if (invoiceFromService && invoiceFromService.team) {
👍

2021-09-08 17:16 UTC, leo-holanda commented on src/app/shared/services/contract.service.ts
> +    const teamSize = invoice.team.length + 1;
Oi Augusto, atualizei essa parte do cloneDeep!

2021-09-10 03:31 UTC, augustoicaro approved these changes

2021-09-10 03:32 UTC, merged

2021-09-10 11:56 UTC, leo-holanda commented on src/app/shared/services/contract.service.ts
> +    const teamSize = invoice.team.length + 1;
👍