Add colaborator's expense and balance columns in contract balance tab
nortan-projetos/plataforma pull request #40
Opened 2021-09-10 15:35 UTC by leo-holanda

2021-09-10 21:46 UTC, augustoicaro requested changes
Faz um rebase no branch com o origin/main por favor e comitta novamente. Tem algo estranho com as suas alterações do `contract.service`

2021-09-10 21:50 UTC, augustoicaro commented on src/app/shared/services/contract.service.ts
> +
Essa parte aqui não faz sentido. Você já tem o `usrService` aqui. Você está fugindo de um dos nossos princípios que é não duplicar a informação para evitar erros. Então esses caras já estão definidos lá. Basta consultar o `_id` deles ou melhor, usar o `isEqual()`

2021-09-10 22:36 UTC, augustoicaro requested changes

2021-09-10 22:36 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/contract-item.component.html
> +          </div>
Experimenta trocar essa parte por

```html
<div class="row irow">
  <div class="col-12 d-flex">
    <div class="col-md-3"><b>Colaborador</b></div>
    <div class="col-md-5 d-flex">
      <div class="col-md-3"><b>Bruto</b></div>
      <div class="col-md-3"><b>Líquido</b></div>
      <div class="col-md-3"><b>%</b></div>
      <div class="col-md-3"><b>Recebido</b></div>
    </div>
    <div class="col-md-4 d-flex">
      <div class="col-md-3"><b>Saldo</b></div>
      <div class="col-md-3"><b>Cashback</b></div>
      <div class="col-md-3"><b>Despesas</b></div>
      <div class="col-md-3"><b>Balanço</b></div>
    </div>
  </div>
</div>
```

2021-09-10 22:36 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/contract-item.component.html
> +          </div>
E repete essa mesma estratégia na parte de baixo. Lendo o código o jeito que você descreveu as coisas não parece intuitivo. Por que tem uma div vazia que ocupa 6 colunas?

2021-09-10 22:36 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/contract-item.component.html
>          </div>
Experimenta usar isso aqui:

```html
<div class="row irow">
  <div class="col-md-12 d-flex">
    <div class="col-md-3">
      {{ userService.idToName(member.user) }}
    </div>
    <div class="col-md-5 d-flex">
      <div class="col-md-3">
        {{
          contractService.toGrossValue(
            contractService.netValueBalance(
              member.distribution,
              contract,
              member.user
            ),
            options.notaFiscal,
            options.nortanPercentage
          )
        }}
      </div>
      <div class="col-md-3">
        {{
          contractService.netValueBalance(
            member.distribution,
            contract,
            member.user
          )
        }}
      </div>
      <div class="col-md-3">
        {{
          contractService.percentageToReceive(
            member.distribution,
            member.user,
            contract
          )
        }}
      </div>
      <div class="col-md-3">
        {{ contractService.receivedValue(member.user, contract) }}
      </div>
    </div>
    <div class="col-md-4 d-flex">
      <div class="col-md-3">
        {{
          contractService.notPaidValue(
            member.distribution,
            member.user,
            contract
          )
        }}
      </div>
      <div class="col-md-3"></div>
      <div class="col-md-3">
        {{
          contractService.getMemberExpensesSum(member.user, contract)
        }}
      </div>
      <div class="col-md-3">
        {{ contractService.getMemberBalance(member.user, contract) }}
      </div>
    </div>
  </div>
</div>
```

A mesma motivação. Por hora não se preocupa com a exibição mobile. Teremos uma estória para isso. Exibição mobile é um ciência. E o que sabemos até hoje é que não é bom rolar elementos quando já temos um scroll vertical. Fica confuso. Ainda mais em tabela com pouco espaço de exibição.

2021-09-13 16:04 UTC, leo-holanda commented
Augusto, notei um problema na hora de adicionar despesas que não tinha antes. É como se as despesas estivessem sendo repartidas. Vou dar uma olhada nisso!

2021-09-13 17:30 UTC, leo-holanda commented on src/app/shared/services/contract.service.ts
> +
👍

2021-09-13 17:30 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/contract-item.component.html
> +          </div>
👍

2021-09-13 17:30 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/contract-item.component.html
>          </div>
👍

2021-09-13 18:12 UTC, leo-holanda commented
> Augusto, notei um problema na hora de adicionar despesas que não tinha antes. É como se as despesas estivessem sendo repartidas quanto antes era individual. Vou dar uma olhada nisso!

Tentei reproduzir aqui e deu tudo certo. Acho que eu só confundi mesmo :thinking:

2021-09-14 13:10 UTC, augustoicaro approved these changes

2021-09-14 13:10 UTC, merged